baseurl = "http://newsunsbox.com"
disableLanguages = ["fr"]
googleAnalytics = ""
summarylength = "20"
paginate = 4
theme = "newsuns-newsite"
title = "New Suns"
publishDir="../../local-build"
[taxonomies]
tag = "tags"
[Languages.en]
contentDir = "content/english"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 3
[[menu.footer]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 4
[[menu.main]]
name = "Login"
url = "https://www.subbly.co/account/auth/login?store=new-suns"
weight = 5
[[menu.main]]
name = "FAQ + Contact"
url = "contact"
weight = 4
[[menu.main]]
name = "Blog"
url = "blog"
weight = 3
[[menu.main]]
name = "Subscribe"
url = "products/subscription-box"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
author = "Themefisher"
contact_form_action = "https://forms.un-static.com/forms/408b3c21f8322e3f546870b14f96baaf44a7d970"
currency = "$"
description = "This is meta description"
logo = "images/logo.png"
logo_width = "130px"
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = true
preloader = ""
[params.subscription]
mailchimp_form_action = "https://newsunsbox.us10.list-manage.com/subscribe/post?u=c80951c35483ed043bb9e9492&amp;id=fe3afb88ef"
mailchimp_form_name = "b_c80951c35483ed043bb9e9492_fe3afb88ef"
